language: python

python:
  - "3.6"
  - "nightly"

install:
  - pip install pytest pytest-cov codecov
  - python setup.py install

script:
  - pytest --cov=.

after_success:
  - codecov

notifications:
    email: false