language: python

python:
  - "3.6"
  - "nightly"

install:
  - pip install pytest codecov

script:
  - coverage run --source npwc_hpc_model -m py.test
  - coverage report

after_success:
  - codecov

notifications:
    email: false