language: python

python:
  - "3.6"
  - "nightly"

install:
  - pip install pytest pytest-cov codecov
  - pip install .

script:
  - pytest --cov nwpc_hpc_model tests

after_success:
  - codecov

notifications:
    email: false